CREATE TABLE IF NOT EXISTS bronze.orders_bronze (
    row_id INTEGER PRIMARY KEY,
    order_id TEXT,
    order_date DATE,
    ship_date DATE,
    ship_mode TEXT,
    customer_id TEXT,
    customer_name TEXT,
    segment TEXT,
    country TEXT,
    city TEXT,
    state TEXT,
    postal_code TEXT,
    region TEXT,
    product_id TEXT,
    category TEXT,
    sub_category TEXT,
    product_name TEXT,
    sales DOUBLE,
    quantity INTEGER,
    discount DOUBLE,
    profit DOUBLE,
    updated_at TIMESTAMP
);
